### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [lirorc/arm-asm-examples#1]
Hello!

I found this project from a comment in https://hackaday.com/2022/10/11/arm-programming-by-example/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by lirorc** [comment]
I don't mind its use in any way. It's just that I couldn't find any license from the original code that I ported from ie. https://github.com/DGivney/assemblytutorials
If there is no problem regarding that I would MIT license it. Thanks for the interest.

**Comment by lirorc** [comment]
License added.

**Comment by vazhnov** [comment]
MIT license — great!
Thank you!
